### ISSUE TITLE
Multiple toggles in a table doesn't work

### ISSUE THREAD

**Issue by vitortmdiniz** [larsmars/vuejs-toggle-switch#15]
## Expected Behavior
Each toggle should work indepentendly

## Actual Behavior
Changing the other toggles will make only the first one to be updated

## Steps to Reproduce the Problem
1 - Add the toggles with a v-for using the same options
  
## Specifications

  - Package version: 1.1.23
  - VueJS Version: 2.5.16

**Comment by vitortmdiniz** [comment]
I just realized the problem is with the label. there will be multiples divs with the same id and the label will activate the first one.

**Comment by larsmars** [comment]
Use group prop with uniq id/index etc for each row.
ie:

```
                    <toggle-switch
                      :options="options"
                      :group="item.ChannelId"
                      @change="toggleInput(item, $event.value)"
                    />
```

**Comment by larsmars** [comment]
Thank you for the feedback let me hear  how it goes

**Comment by larsmars** [comment]
Solution provided, no more feedback from user, closing this

**Comment by vitortmdiniz** [comment]
It did work, thanks :)

**Comment by BhanuReddy95** [comment]
@larsmars how will the preSelected work for multiple toggles with a group property?
