### ISSUE TITLE
Error on multiple switchers with same labels

### ISSUE THREAD

**Issue by durancu** [larsmars/vuejs-toggle-switch#18]
## Expected Behavior
Multiple switchers with labels yes/no should work properly/

## Actual Behavior

 **Without :group**
- First switcher work fine but the other, when you click on them, that actually changes the value of the first one instead.
 
**With :group** 
- The switchers freezes

## Steps to Reproduce the Problem
  Set two switchers with items property like:
```
 items: {
   delay: .4,
   disabled: false,
     labels: [
     {name: 'No', color: '#d0d0d0', backgroundColor: '#777777'},
     {name: 'Yes', color: '#ffffff', backgroundColor: '#333333'}
     ]
 }
```
Switchers html:

Number 1:
 ```
<toggle-switch name="married" :options="toggles.married" v-model="user.married" :group="'married'" />
```

Number 2:
 ```
<toggle-switch name="insured" :options="toggles.insured" v-model="user.insured" :group="'insured'" />```


## Specifications

  - Package version: latest
  - VueJS Version: 2.1

**Comment by larsmars** [comment]
The bug is updated in v. 1.1.29

I also added a demo with use of list, group, name and 2 way binding at det live demo:
https://softwarefun.no/toggleswitch

Thank you for the feedback.
