### ISSUE TITLE
Add Values to Labels object

### ISSUE THREAD

**Issue by jessemarple** [larsmars/vuejs-toggle-switch#20]
https://github.com/larsmars/vuejs-toggle-switch/blob/11b1de13dbcc3d60169fc41e590c076d9bf0f223/src/ToggleSwitch.vue#L11

## Expected Behavior
In some cases, you may want to present a word - e.g. Enabled, Disabled - when you'd want the value to be something else - e.g. 1, true, etc. 

## Actual Behavior
Presently, it appears that the value is set to the label.name property.

**Comment by jessemarple** [comment]
I may solve this one by making some edits and submitting a pull request if you don't mind.

**Comment by larsmars** [comment]
Hi, value and label.name is tightly coupled yes.

Translating of value to something else can be done thru computed properties. IE:  You want to present a word Enabled/Disabled on the switch and you want value to be something else.

  computed: {
    switchValue() {
      return this.value === 'Enabled' ? 1 : 0
    }
  }

The challenge is to not over complicate, make easy to use  and include good functionality.
Functionality should work fine for 2 switch labels but also for 17. different switch labels.

Feel free to make an suggestion/example/pr, then I'll look at it.

Thank you for the feedback.

**Comment by larsmars** [comment]
No feedback from user, closing this.
