### ISSUE TITLE
How will the preSelected work for multiple toggles with a group property?

### ISSUE THREAD

**Issue by BhanuReddy95** [larsmars/vuejs-toggle-switch#21]
_Originallyriginally posted by @BhanuReddy95 in https://github.com/larsmars/vuejs-toggle-switch/issue_comments#issuecomment-439853150_

@larsmars 
I wanted my toggle's to have a preSelected value. preSelected with a single toggle is working fine. But with many toggles and a group it is not working. please provide me the solution ASAP......

**Comment by BhanuReddy95** [comment]
creating a new issue with screenshots. Hence closing this

**Comment by larsmars** [comment]
Hi, the demo is using multiple toggles, group and preSelected ( https://softwarefun.no/#/toggleswitch ) 
Show me the code and I will help you.

**Comment by BhanuReddy95** [comment]
Hi, in the demo the pre selected value is Female for all the three toggles(Jack, John and Joe). I guess myOptions.items.preSelected is set to Female. I need Male to be pre selected for the second row(John). How to do that?

**Comment by larsmars** [comment]
duplicate
