### ISSUE TITLE
How to preSelect when multiple toggle exists on a same page.

### ISSUE THREAD

**Issue by BhanuReddy95** [larsmars/vuejs-toggle-switch#22]
## Expected Behavior
preSelected prop when used, highlights the button with the selected value on load. When multiple toggle switches are loaded in a same page, each toggle switch should highlight its button with a different value defined (something like group should be there to distinguish).

## Actual Behavior
preSelected prop when used, highlights the button with the selected value on load. When multiple toggle switches are loaded in a same page, each toggle switch is highlighting with the same value assigned to preSelected prop.(If myOptions.items.preSelected = 'OR', then all the toogle-switches are highlighted with "OR")

![createdepcrop](https://user-images.githubusercontent.com/45167487/48791664-83aa0a80-ecf2-11e8-8e68-a0e27cd7eaa0.png)

The above screen is developed setting the group prop to a different values for each toggle. Every time the user clicks on a plus icon, a new row is added along with a new toggle. Now, "AND" or "OR" is selected by the user and then the values are saved to the database.
`  <toggle-switch
          :options="myOptions"
          :group="row.switchGroup"
          @change="row.condition = $event.value">
    </toggle-switch>`

![retrivedeporcrop](https://user-images.githubusercontent.com/45167487/48791678-8c9adc00-ecf2-11e8-9530-4f02a1b1e84d.png)

The above screen is resulted when i am trying to fetch the values from the db and assigning it to the toggle-switches, all the toggle-switches are highlighted with "OR" upon assigning the "this.myOptions.items.preSelected = "row.condition", but I want them to highlight with their own previously defined values. All the toggles are defaulted to "OR". 

@larsmars @lauri jalonen and @baltom 
please create a prop something like group prop which will differenciate one toggle from another so that each toggle-switch is assgined with some pre-selected value.

**Comment by larsmars** [comment]
> when i am trying to fetch the values from the db and assigning it to the toggle-switches

>  I want them to highlight with their own previously defined values

You can use 2-way binding for this.

```
      <ul id="list">
        <li v-for="(user, index) in users" :key="index">
          {{ user.name }} is a {{ user.sex }}
          <toggle-switch
            :name="'name'"
            :group="user.name"
            :options='options'
            v-model='user.sex'
          />
        </li>
      </ul>
```

If user.sex is Male,  male will be pre-set if user.sex is female female will be pre-set.
If user.sex is not set none will be pre-set

**Comment by BhanuReddy95** [comment]
Hi @larsmars 
after using v-model, the value of user.sex is overridden with the value of user.name(which is the group value). i.e. the html is not rendering "John is Male", it is rendering as "John is John" and the toggle-switches are not pre-set with any value.

**Comment by larsmars** [comment]
ehe..
I added another example for you at the demo site
data set:
```
      cars: [
        { name: 'Audi', gear: 'Manual' },
        { name: 'Bmw', gear: '' },
        { name: 'Tesla', gear: 'Auto' }
      ]
```
This works as described and you can test it.

**Comment by BhanuReddy95** [comment]
Hi , 

below is the code which is written for testing.

`<template>`
     `<ul id="list">`
       `<li v-for="(car, index) in cars" :key="index">`
          `{{ car.name }} is a {{ car.gear }}`
         `<toggle-switch`
            `:name="'name'"`
            `:group="car.name"`
            `:options="myOptions"`
            `v-model='car.gear'`
         `/>`
        `</li>`
      `</ul>`
`</template>`

`<script>`
`import ToggleSwitch from 'vuejs-toggle-switch'`
`export default {`
    `data: function()`
    `{`
        `return{`
             `cars:` 
             `[`
                `{ name: 'Audi', gear: 'Manual' },`
                `{ name: 'Bmw', gear: '' },`
                `{ name: 'Tesla', gear: 'Auto' }`
             `],`
            `myOptions: `
            `{`
                `layout: `
                `{`
                    `color: 'black',`
                    `backgroundColor: 'lightgray',`
                    `selectedColor: 'white',`
                    `selectedBackgroundColor: 'green',`
                   `borderColor: 'black',`
                    `fontFamily: 'Arial',`
                    `fontWeight: 'normal',`
                    `fontWeightSelected: 'bold',`
                    `squareCorners: false,`
                    `noBorder: false`
                `},`
                `size: `
                `{`
                    `fontSize: 14,`
                    `height: 34,`
                    `padding: 7,`
                    `width: 150`
                `},`
                `items: `
                `{`
                    `delay: .4,`
                    `preSelected: 'unknown',`
                    `disabled: false,`
                    `labels: [`
                    `{name: 'Auto', color: 'white', backgroundColor: 'red'}, `
                    `{name: 'Manual', color: 'white', backgroundColor: 'green'}`
                    `]`
                `}`
            `}`
       `}`
    `}`
`}`
`</script>`


The below is the output for the above code.
![pocoutcome](https://user-images.githubusercontent.com/45167487/48883548-97538f00-ee20-11e8-9dad-b315e9df2a16.png)

##Observations

- **car.gear** changed to **car.gear+car.name**
- None of the switches have been pre-selected with the values (either Auto or Manual).
- I have to double-click if want to select any option other than v-model. It should be single click. 

@larsmars 
Please go through the code and notify me about the changes to incorporate for the code to work like yours. 

Thanks

**Comment by larsmars** [comment]
Import and use the dependency in your main file.
Now you are importing and not using the dependency in component.

Working demo with your code:
https://codesandbox.io/s/lyvllx33w9

**Comment by larsmars** [comment]
Solution provided, case closed.
Use the forum.vuejs.org for feature guidance

**Comment by BhanuReddy95** [comment]
Hi, 
I have additionally written the import statement. The issue was not with dependency not being used. I have included it in the main.js
I was using the older version of your plugin 1.1.23, when I updated it to 1.1.31 it was working. 
Sorry for not checking. Thanks for your patience and responses
