### ISSUE TITLE
Using locally, not globally?

### ISSUE THREAD

**Issue by iamvitali** [larsmars/vuejs-toggle-switch#23]
## Expected Behavior
Is there a way to import the plugin at the component level and not globally?

## Actual Behavior
Currently it throws an error: `[Vue warn]: Failed to mount component: template or render function not defined.`

## Steps to Reproduce the Problem
  1. Install plugin via npm.
  1. Inside the component add:
```
import ToggleSwitch from 'vuejs-toggle-switch';
export default {
    components: {
        ToggleSwitch,
    },
    ....
```

## Specifications

  - Package version: 1.1.31
  - VueJS Version: 2.5.16

**Comment by larsmars** [comment]
No, but you can create a wrapper to do this.
