### ISSUE TITLE
Some Bug

### ISSUE THREAD

**Issue by angemirano** [larsmars/vuejs-toggle-switch#26]
## Expected Behavior
When selecting, put the color configured on the button
[https://a.imge.to/2019/07/18/1Dsm4.png](https://a.imge.to/2019/07/18/1Dsm4.png)
[https://b.imge.to/2019/07/18/1Dvi2.png](https://b.imge.to/2019/07/18/1Dvi2.png)
## Actual Behavior
The event is executed but the color is not painted to the button.

## Steps to Reproduce the Problem

  1. Put toggle-switch inside v-data-table.
  2. Set "myOptions" options by default with an extra item.
  3. Clic in any button.

## Specifications

  - Package version: latest
  - VueJS Version: latest

**Comment by larsmars** [comment]
Please verify you are at version 1.3.0
What is you config/options for the switch?
Can you provide code where it is used?
Switch is working as intended at demo site: https://softwarefun.no/#/toggleswitch

**Comment by angemirano** [comment]
Of course

**Data Table**

`<v-data-table>
...
              <td style=" height: 35px;" class="text-xs-center caption">
                <toggle-switch
                  :options="myOptions"
                  :disabled="false"
                  @change="CambiarAprobacion($event.value, props.item.myId)"
                  :name="nombreSwitch + props.item.myId" 
                   />
              </td>
...
</v-data-table>`

**Data Return**

`myOptions: {
        layout: {
          color: 'black',
          backgroundColor: 'lightgray',
          selectedColor: 'white',
          selectedBackgroundColor: 'green',
          borderColor: 'black',
          fontFamily: 'Arial',
          fontWeight: 'normal',
          fontWeightSelected: 'bold',
          squareCorners: false,
          noBorder: false,
        },
        size: {
          fontSize: 0.9,
          height: 2,
          padding: 0.3,
          width: 17
        },
        items: {
          delay: .4,
          preSelected: 'unknown',
          disabled: false,
          labels: [
            {name: 'New', color: 'white', backgroundColor: 'orange'}, 
            {name: 'Good', color: 'white', backgroundColor: 'blue'},
            {name: 'Bad', color: 'white', backgroundColor: 'red'}
          ]
        }
      },
      nombreSwitch: 'AC'`

**Comment by angemirano** [comment]
> 
> 
> Please verify you are at version 1.3.0
> What is you config/options for the switch?
> Can you provide code where it is used?
> Switch is working as intended at demo site: https://softwarefun.no/#/toggleswitch

**Comment by angemirano** [comment]
> 
> 
> Please verify you are at version 1.3.0
> What is you config/options for the switch?
> Can you provide code where it is used?
> Switch is working as intended at demo site: https://softwarefun.no/#/toggleswitch

Of course

Data Table

<v-data-table> ... <td style=" height: 35px;" class="text-xs-center caption"> <toggle-switch :options="myOptions" :disabled="false" @change="CambiarAprobacion($event.value, props.item.myId)" :name="nombreSwitch + props.item.myId" /> </td> ... </v-data-table>

Data Return

myOptions: { layout: { color: 'black', backgroundColor: 'lightgray', selectedColor: 'white', selectedBackgroundColor: 'green', borderColor: 'black', fontFamily: 'Arial', fontWeight: 'normal', fontWeightSelected: 'bold', squareCorners: false, noBorder: false, }, size: { fontSize: 0.9, height: 2, padding: 0.3, width: 17 }, items: { delay: .4, preSelected: 'unknown', disabled: false, labels: [ {name: 'New', color: 'white', backgroundColor: 'orange'}, {name: 'Good', color: 'white', backgroundColor: 'blue'}, {name: 'Bad', color: 'white', backgroundColor: 'red'} ] } }, nombreSwitch: 'AC'
