### ISSUE TITLE
一个界面使用了两个toggle-switch出现问题

### ISSUE THREAD

**Issue by TongCong** [larsmars/vuejs-toggle-switch#36]
<toggle-switch :id="'111'" :name="'111'" :options="generalTaskStatisticsOptions" class="jk-time-toggle" @change="generalTaskStatisticsChange($event.value)"/>

<toggle-switch :id="'222'" :name="'222'" :options="taskStatisticsOptions" class="jk-time-toggle" @change="financeRevenueChange($event.value)"/>

我在一个界面使用两个，点击下面的控件，触发了上面的generalTaskStatisticsChange方法，请问这是什么原因导致的

**Comment by larsmars** [comment]
请用英文
If you use multiple switches in the same iterface, use groups prop, ses readme file:
`:group="switchGroup" // This is optional, use if multiple toggle-switch on same page with same label names`
